### ISSUE TITLE
Can't track my account, console shows following error : "has been blocked by CORS policy..."

### ISSUE THREAD

**Issue by NouemanKHAL** [mari-linhares/UVaCPTracker#1]
Hi, I was struggling to track my progress so I reinstalled the app, cleared my browser's data then found this error in chrome's console :
![image](https://user-images.githubusercontent.com/25211181/48209170-c2e06f00-e374-11e8-9488-546fbda1ac5f.png)

**Comment by hereismari** [comment]
Hi @NouemanKHAL,

I think a permission in the manifest.json file should fix it. Will try to have a look on the weekend. Feel free to send a PR if you feel this is urgent.

Thank you!

**Comment by hereismari** [comment]
Release version 1.0.3, error should be fixed.
